nelmio_cors:
    defaults:
        origin_regex: false
        allow_origin: ['https://127.0.0.1:5173', 'http://127.0.0.1:5173', 'http://localhost:5173', 'https://localhost:8000']
        allow_methods: ['GET', 'OPTIONS', 'POST', 'PUT', 'PATCH', 'DELETE']
        allow_headers: ['Content-Type', 'Authorization']
        expose_headers: ['Link']
        max_age: 3600
        allow_credentials: true
    paths:
        '^/api/':
            allow_origin: ['https://127.0.0.1:5173', 'http://127.0.0.1:5173', 'http://localhost:5173', 'https://localhost:8000']
            allow_headers: ['Content-Type', 'Authorization']
            allow_methods: ['POST', 'PUT', 'GET', 'DELETE', 'OPTIONS']
            allow_credentials: true